name: Deraj Fotografie
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73948
title: 'a glimpse through my viewfinder, 35mm photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf7f4'
    - '#2a241f'
    - '#a8aca6'
    - '#5f4030'
    - '#b88b55'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
