name: Deraj Fotografie
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73948
title: 'a glimpse through my viewfinder, 35mm photography'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292522'
    - '#fcfcfc'
    - '#bd772f'
    - '#f7e0a3'
    - '#e7b85a'
  brandStrength: 0.875
  lightness: 0.0625
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
